import { Product } from '@/types/product';

export const sampleProducts: Omit<Product, 'productId' | 'businessId' | 'metadata'>[] = [
  {
    name: "Wireless Bluetooth Headphones",
    description: "High-quality wireless headphones with noise cancellation and 30-hour battery life. Perfect for music lovers and professionals.",
    sku: "WBH-001",
    barcode: "1234567890123",
    pricing: {
      cost: 45.00,
      price: 89.99,
      compareAtPrice: 129.99,
      currency: "USD",
    },
    inventory: {
      trackInventory: true,
      quantity: 150,
      lowStockAlert: 20,
      stockLocations: [
        { location: "Main Warehouse", quantity: 120 },
        { location: "Store Front", quantity: 30 },
      ],
    },
    category: "electronics",
    tags: ["wireless", "bluetooth", "headphones", "audio", "noise-cancellation"],
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500",
      "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=500",
    ],
    variants: [
      {
        variantId: "variant_1",
        name: "Black",
        sku: "WBH-001-BLK",
        barcode: "1234567890124",
        price: 89.99,
        cost: 45.00,
        quantity: 80,
        attributes: { Color: "Black" },
        images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500"],
        isActive: true,
      },
      {
        variantId: "variant_2",
        name: "White",
        sku: "WBH-001-WHT",
        barcode: "1234567890125",
        price: 89.99,
        cost: 45.00,
        quantity: 70,
        attributes: { Color: "White" },
        images: ["https://images.unsplash.com/photo-1583394838336-acd977736f90?w=500"],
        isActive: true,
      },
    ],
    status: "active",
    seo: {
      title: "Wireless Bluetooth Headphones - Premium Audio",
      description: "Experience premium audio with our wireless Bluetooth headphones featuring noise cancellation and 30-hour battery life.",
      keywords: ["wireless headphones", "bluetooth", "noise cancellation", "audio", "music"],
    },
  },
  {
    name: "Organic Cotton T-Shirt",
    description: "Comfortable 100% organic cotton t-shirt. Perfect fit, breathable fabric, and sustainable production. Available in multiple colors.",
    sku: "CTS-001",
    barcode: "2345678901234",
    pricing: {
      cost: 8.50,
      price: 24.99,
      compareAtPrice: 34.99,
      currency: "USD",
    },
    inventory: {
      trackInventory: true,
      quantity: 300,
      lowStockAlert: 50,
      stockLocations: [
        { location: "Main Warehouse", quantity: 250 },
        { location: "Store Front", quantity: 50 },
      ],
    },
    category: "clothing",
    tags: ["organic", "cotton", "t-shirt", "sustainable", "comfortable"],
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500",
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=500",
    ],
    variants: [
      {
        variantId: "variant_3",
        name: "Small - Navy",
        sku: "CTS-001-S-NV",
        barcode: "2345678901235",
        price: 24.99,
        cost: 8.50,
        quantity: 60,
        attributes: { Size: "Small", Color: "Navy" },
        images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500"],
        isActive: true,
      },
      {
        variantId: "variant_4",
        name: "Medium - White",
        sku: "CTS-001-M-WHT",
        barcode: "2345678901236",
        price: 24.99,
        cost: 8.50,
        quantity: 80,
        attributes: { Size: "Medium", Color: "White" },
        images: ["https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=500"],
        isActive: true,
      },
      {
        variantId: "variant_5",
        name: "Large - Black",
        sku: "CTS-001-L-BLK",
        barcode: "2345678901237",
        price: 24.99,
        cost: 8.50,
        quantity: 90,
        attributes: { Size: "Large", Color: "Black" },
        images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500"],
        isActive: true,
      },
      {
        variantId: "variant_6",
        name: "XL - Gray",
        sku: "CTS-001-XL-GRY",
        barcode: "2345678901238",
        price: 24.99,
        cost: 8.50,
        quantity: 70,
        attributes: { Size: "XL", Color: "Gray" },
        images: ["https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=500"],
        isActive: true,
      },
    ],
    status: "active",
    seo: {
      title: "Organic Cotton T-Shirt - Sustainable Fashion",
      description: "Comfortable 100% organic cotton t-shirt with perfect fit and breathable fabric. Sustainable production.",
      keywords: ["organic cotton", "t-shirt", "sustainable", "clothing", "comfortable"],
    },
  },
  {
    name: "Professional Coffee Maker",
    description: "High-end coffee maker with programmable settings, thermal carafe, and built-in grinder. Perfect for coffee enthusiasts.",
    sku: "PCM-001",
    barcode: "3456789012345",
    pricing: {
      cost: 120.00,
      price: 249.99,
      compareAtPrice: 299.99,
      currency: "USD",
    },
    inventory: {
      trackInventory: true,
      quantity: 25,
      lowStockAlert: 5,
      stockLocations: [
        { location: "Main Warehouse", quantity: 20 },
        { location: "Store Front", quantity: 5 },
      ],
    },
    category: "home",
    tags: ["coffee", "kitchen", "appliance", "programmable", "grinder"],
    images: [
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=500",
      "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500",
    ],
    variants: [],
    status: "active",
    seo: {
      title: "Professional Coffee Maker - Programmable with Grinder",
      description: "High-end coffee maker with programmable settings, thermal carafe, and built-in grinder for coffee enthusiasts.",
      keywords: ["coffee maker", "programmable", "grinder", "kitchen", "appliance"],
    },
  },
  {
    name: "Fitness Tracker Smartwatch",
    description: "Advanced fitness tracker with heart rate monitoring, GPS, sleep tracking, and 7-day battery life. Waterproof design.",
    sku: "FTS-001",
    barcode: "4567890123456",
    pricing: {
      cost: 85.00,
      price: 179.99,
      compareAtPrice: 229.99,
      currency: "USD",
    },
    inventory: {
      trackInventory: true,
      quantity: 75,
      lowStockAlert: 15,
      stockLocations: [
        { location: "Main Warehouse", quantity: 60 },
        { location: "Store Front", quantity: 15 },
      ],
    },
    category: "electronics",
    tags: ["fitness", "smartwatch", "health", "gps", "heart-rate"],
    images: [
      "https://images.unsplash.com/photo-1579586337278-3f436f25f4d5?w=500",
      "https://images.unsplash.com/photo-1544117519-31a4b719223d?w=500",
    ],
    variants: [
      {
        variantId: "variant_7",
        name: "Black Sport Band",
        sku: "FTS-001-BLK",
        barcode: "4567890123457",
        price: 179.99,
        cost: 85.00,
        quantity: 40,
        attributes: { Color: "Black", Band: "Sport" },
        images: ["https://images.unsplash.com/photo-1579586337278-3f436f25f4d5?w=500"],
        isActive: true,
      },
      {
        variantId: "variant_8",
        name: "Pink Sport Band",
        sku: "FTS-001-PNK",
        barcode: "4567890123458",
        price: 179.99,
        cost: 85.00,
        quantity: 35,
        attributes: { Color: "Pink", Band: "Sport" },
        images: ["https://images.unsplash.com/photo-1544117519-31a4b719223d?w=500"],
        isActive: true,
      },
    ],
    status: "active",
    seo: {
      title: "Fitness Tracker Smartwatch - GPS & Heart Rate Monitor",
      description: "Advanced fitness tracker with heart rate monitoring, GPS, sleep tracking, and 7-day battery life.",
      keywords: ["fitness tracker", "smartwatch", "gps", "heart rate", "health"],
    },
  },
  {
    name: "Artisan Ceramic Mug",
    description: "Handcrafted ceramic mug with unique glaze patterns. Perfect for coffee, tea, or hot chocolate. Microwave and dishwasher safe.",
    sku: "ACM-001",
    barcode: "5678901234567",
    pricing: {
      cost: 6.50,
      price: 18.99,
      compareAtPrice: 24.99,
      currency: "USD",
    },
    inventory: {
      trackInventory: true,
      quantity: 120,
      lowStockAlert: 25,
      stockLocations: [
        { location: "Main Warehouse", quantity: 100 },
        { location: "Store Front", quantity: 20 },
      ],
    },
    category: "home",
    tags: ["ceramic", "mug", "handcrafted", "artisan", "coffee"],
    images: [
      "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=500",
      "https://images.unsplash.com/photo-1514228742587-6b1558fcf93a?w=500",
    ],
    variants: [
      {
        variantId: "variant_9",
        name: "Blue Glaze",
        sku: "ACM-001-BLU",
        barcode: "5678901234568",
        price: 18.99,
        cost: 6.50,
        quantity: 40,
        attributes: { Glaze: "Blue" },
        images: ["https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=500"],
        isActive: true,
      },
      {
        variantId: "variant_10",
        name: "Green Glaze",
        sku: "ACM-001-GRN",
        barcode: "5678901234569",
        price: 18.99,
        cost: 6.50,
        quantity: 35,
        attributes: { Glaze: "Green" },
        images: ["https://images.unsplash.com/photo-1514228742587-6b1558fcf93a?w=500"],
        isActive: true,
      },
      {
        variantId: "variant_11",
        name: "Brown Glaze",
        sku: "ACM-001-BRN",
        barcode: "5678901234570",
        price: 18.99,
        cost: 6.50,
        quantity: 45,
        attributes: { Glaze: "Brown" },
        images: ["https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=500"],
        isActive: true,
      },
    ],
    status: "active",
    seo: {
      title: "Artisan Ceramic Mug - Handcrafted Unique Glaze",
      description: "Handcrafted ceramic mug with unique glaze patterns. Perfect for coffee, tea, or hot chocolate.",
      keywords: ["ceramic mug", "handcrafted", "artisan", "coffee mug", "unique"],
    },
  },
  {
    name: "Wireless Phone Charger",
    description: "Fast wireless charging pad with LED indicator and non-slip surface. Compatible with all Qi-enabled devices.",
    sku: "WPC-001",
    barcode: "6789012345678",
    pricing: {
      cost: 15.00,
      price: 39.99,
      compareAtPrice: 49.99,
      currency: "USD",
    },
    inventory: {
      trackInventory: true,
      quantity: 200,
      lowStockAlert: 30,
      stockLocations: [
        { location: "Main Warehouse", quantity: 170 },
        { location: "Store Front", quantity: 30 },
      ],
    },
    category: "electronics",
    tags: ["wireless", "charger", "phone", "qi", "fast-charging"],
    images: [
      "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=500",
    ],
    variants: [],
    status: "active",
    seo: {
      title: "Wireless Phone Charger - Fast Qi Charging Pad",
      description: "Fast wireless charging pad with LED indicator and non-slip surface. Compatible with all Qi-enabled devices.",
      keywords: ["wireless charger", "phone charger", "qi", "fast charging", "wireless"],
    },
  },
  {
    name: "Premium Yoga Mat",
    description: "Non-slip premium yoga mat with carrying strap. Made from eco-friendly materials with excellent grip and cushioning.",
    sku: "PYM-001",
    barcode: "7890123456789",
    pricing: {
      cost: 25.00,
      price: 59.99,
      compareAtPrice: 79.99,
      currency: "USD",
    },
    inventory: {
      trackInventory: true,
      quantity: 80,
      lowStockAlert: 15,
      stockLocations: [
        { location: "Main Warehouse", quantity: 65 },
        { location: "Store Front", quantity: 15 },
      ],
    },
    category: "sports",
    tags: ["yoga", "mat", "fitness", "eco-friendly", "non-slip"],
    images: [
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500",
    ],
    variants: [
      {
        variantId: "variant_12",
        name: "Purple",
        sku: "PYM-001-PUR",
        barcode: "7890123456790",
        price: 59.99,
        cost: 25.00,
        quantity: 30,
        attributes: { Color: "Purple" },
        images: ["https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500"],
        isActive: true,
      },
      {
        variantId: "variant_13",
        name: "Blue",
        sku: "PYM-001-BLU",
        barcode: "7890123456791",
        price: 59.99,
        cost: 25.00,
        quantity: 25,
        attributes: { Color: "Blue" },
        images: ["https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500"],
        isActive: true,
      },
      {
        variantId: "variant_14",
        name: "Gray",
        sku: "PYM-001-GRY",
        barcode: "7890123456792",
        price: 59.99,
        cost: 25.00,
        quantity: 25,
        attributes: { Color: "Gray" },
        images: ["https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500"],
        isActive: true,
      },
    ],
    status: "active",
    seo: {
      title: "Premium Yoga Mat - Eco-Friendly Non-Slip",
      description: "Non-slip premium yoga mat with carrying strap. Made from eco-friendly materials with excellent grip.",
      keywords: ["yoga mat", "premium", "eco-friendly", "non-slip", "fitness"],
    },
  },
  {
    name: "LED Desk Lamp",
    description: "Adjustable LED desk lamp with touch controls and USB charging port. Perfect for home office or study space.",
    sku: "LDL-001",
    barcode: "8901234567890",
    pricing: {
      cost: 22.00,
      price: 49.99,
      compareAtPrice: 69.99,
      currency: "USD",
    },
    inventory: {
      trackInventory: true,
      quantity: 60,
      lowStockAlert: 10,
      stockLocations: [
        { location: "Main Warehouse", quantity: 50 },
        { location: "Store Front", quantity: 10 },
      ],
    },
    category: "home",
    tags: ["led", "lamp", "desk", "adjustable", "usb"],
    images: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500",
    ],
    variants: [],
    status: "active",
    seo: {
      title: "LED Desk Lamp - Adjustable with USB Charging",
      description: "Adjustable LED desk lamp with touch controls and USB charging port. Perfect for home office.",
      keywords: ["led lamp", "desk lamp", "adjustable", "usb charging", "office"],
    },
  },
  {
    name: "Stainless Steel Water Bottle",
    description: "Insulated stainless steel water bottle that keeps drinks cold for 24 hours or hot for 12 hours. Leak-proof design.",
    sku: "SSW-001",
    barcode: "9012345678901",
    pricing: {
      cost: 12.00,
      price: 29.99,
      compareAtPrice: 39.99,
      currency: "USD",
    },
    inventory: {
      trackInventory: true,
      quantity: 180,
      lowStockAlert: 40,
      stockLocations: [
        { location: "Main Warehouse", quantity: 150 },
        { location: "Store Front", quantity: 30 },
      ],
    },
    category: "sports",
    tags: ["water bottle", "stainless steel", "insulated", "leak-proof", "eco-friendly"],
    images: [
      "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500",
    ],
    variants: [
      {
        variantId: "variant_15",
        name: "Silver",
        sku: "SSW-001-SLV",
        barcode: "9012345678902",
        price: 29.99,
        cost: 12.00,
        quantity: 80,
        attributes: { Color: "Silver" },
        images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500"],
        isActive: true,
      },
      {
        variantId: "variant_16",
        name: "Black",
        sku: "SSW-001-BLK",
        barcode: "9012345678903",
        price: 29.99,
        cost: 12.00,
        quantity: 100,
        attributes: { Color: "Black" },
        images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500"],
        isActive: true,
      },
    ],
    status: "active",
    seo: {
      title: "Stainless Steel Water Bottle - Insulated 24hr Cold",
      description: "Insulated stainless steel water bottle that keeps drinks cold for 24 hours. Leak-proof design.",
      keywords: ["water bottle", "stainless steel", "insulated", "leak-proof", "eco-friendly"],
    },
  },
  {
    name: "Bluetooth Speaker",
    description: "Portable Bluetooth speaker with 360-degree sound and 12-hour battery life. Waterproof design for outdoor use.",
    sku: "BTS-001",
    barcode: "0123456789012",
    pricing: {
      cost: 35.00,
      price: 79.99,
      compareAtPrice: 99.99,
      currency: "USD",
    },
    inventory: {
      trackInventory: true,
      quantity: 45,
      lowStockAlert: 8,
      stockLocations: [
        { location: "Main Warehouse", quantity: 35 },
        { location: "Store Front", quantity: 10 },
      ],
    },
    category: "electronics",
    tags: ["bluetooth", "speaker", "portable", "waterproof", "360-degree"],
    images: [
      "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500",
    ],
    variants: [
      {
        variantId: "variant_17",
        name: "Black",
        sku: "BTS-001-BLK",
        barcode: "0123456789013",
        price: 79.99,
        cost: 35.00,
        quantity: 25,
        attributes: { Color: "Black" },
        images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500"],
        isActive: true,
      },
      {
        variantId: "variant_18",
        name: "Blue",
        sku: "BTS-001-BLU",
        barcode: "0123456789014",
        price: 79.99,
        cost: 35.00,
        quantity: 20,
        attributes: { Color: "Blue" },
        images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500"],
        isActive: true,
      },
    ],
    status: "active",
    seo: {
      title: "Bluetooth Speaker - Portable 360° Sound Waterproof",
      description: "Portable Bluetooth speaker with 360-degree sound and 12-hour battery life. Waterproof design.",
      keywords: ["bluetooth speaker", "portable", "360-degree", "waterproof", "battery"],
    },
  },
];

export const sampleCategories = [
  { name: "Electronics", description: "Electronic devices and accessories" },
  { name: "Clothing", description: "Apparel and fashion items" },
  { name: "Home", description: "Home and kitchen products" },
  { name: "Sports", description: "Sports and fitness equipment" },
  { name: "Books", description: "Books and educational materials" },
  { name: "Beauty", description: "Beauty and personal care products" },
  { name: "Automotive", description: "Automotive parts and accessories" },
  { name: "Toys", description: "Toys and games" },
];

export const generateSampleCSV = () => {
  const headers = [
    "name",
    "description", 
    "sku",
    "barcode",
    "category",
    "cost",
    "price",
    "quantity",
    "low_stock_alert",
    "status"
  ];
  
  const rows = sampleProducts.map(product => [
    `"${product.name}"`,
    `"${product.description}"`,
    `"${product.sku}"`,
    `"${product.barcode}"`,
    `"${product.category}"`,
    product.pricing.cost.toString(),
    product.pricing.price.toString(),
    product.inventory.quantity.toString(),
    product.inventory.lowStockAlert.toString(),
    `"${product.status}"`
  ]);
  
  return [headers.join(","), ...rows.map(row => row.join(","))].join("\n");
};
